repos:
  - repo: local
    hooks:
      - id: unit-tests
        name: Run unit tests
        entry: ./gradlew test
        language: system
        stages: [pre-commit]
        pass_filenames: false
        
      - id: ktlint-check
        name: Run ktlint check
        entry: ./gradlew ktlintCheck
        language: system
        stages: [pre-commit]
        pass_filenames: false
        
      - id: detekt
        name: Run detekt
        entry: ./gradlew detekt
        language: system
        stages: [pre-commit]
        pass_filenames: false